name: myapprun
description: "A new Flutter project."
publish_to: 'none'
version: 1.2.2+22

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.5.3
  shared_preferences: ^2.2.3
  flutter_launcher_icons: ^0.14.4
  flutter_staggered_grid_view: ^0.7.0
    # ... (بقية حزمك) ...
  video_player: ^2.8.6

    # --- أضف هذا السطر ---
  url_launcher: ^6.3.1
    # --- نهاية الإضافة ---

  # حزم الفيديو
  # حزم Firebase (تم التحديث لإصدارات حديثة متوافقة مع Flutter 3.x)
  #firebase_core: ^2.25.3
  #firebase_messaging: ^14.7.19

  # حزمة التواريخ والتدويل
  intl: ^0.19.0
  uuid: ^4.5.2
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_messaging: ^16.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # حزمة الشاشة الافتتاحية
  flutter_native_splash: ^2.4.0 # تم إلغاء التعليق

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true

  assets:
    - assets/images/all_category.png
    - assets/images/shopping_girl.png
    # تأكد من إضافة مسار الأيقونة هنا أيضاً
    - assets/icons/VelinLogo.png

# === إعدادات حزمة أيقونة التطبيق (App Icon) ===
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/VelinLogo.png"
  min_sdk_android: 21

# === إعدادات حزمة الشاشة الافتتاحية (Native Splash Screen) ===
flutter_native_splash:
  # لون الخلفية (استخدم نفس اللون البرتقالي لشعارك)
  color: "#ffffff"
  # صورة الشعار (استخدم نفس مسار أيقونة التطبيق)
  image: assets/icons/VelinSplash.png
  # إعدادات إضافية (اختياري)
  android: true
  ios: true